services:
  - type: web
    name: walletx-backend
    env: node
    plan: free
    region: oregon  # Change if needed: frankfurt, singapore, etc.
    branch: main    # or 'master' or whatever your main branch is
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Ensure this matches your app.listen(PORT)
      - key: CORS_ALLOWED_ORIGINS
        value: 'https://wallet-x-app.vercel.app,https://walletx.afzaldev.in,https://walletx.afzalmir.me,http://localhost:5173'
